defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Assay table with sequence column + raw objectives.
data: example_scripts/data/comprehensive_double_mutant_assay.tsv

# Path to a trained Kermut checkpoint (.pt) compatible with the assay features.
checkpoint: path/to/kermut_checkpoint.pt

# Multi-objective configuration: activity is maximised, aggregation minimised.
objectives:
  - activity_score
  - aggregation_penalty

# Direction per objective ("max" or "min").
directions:
  - max
  - min

# Relative preference for each objective when constructing scalar surrogate values.
weights:
  - 0.6
  - 0.4

# Optimisation hyper-parameters forwarded to scripts.bopo_policy_learning.suggest.
epochs: 30
B: 256
K: 24
batch_size: 96
min_muts: 2
max_muts: 8
site_pool: null
lr: 0.05
seed: 123
device: cpu
base_seq: null
out_csv: outputs/bopo_candidates.csv

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
